### ISSUE TITLE
fix: TypeError: Object of type date is not JSON serializable

### ISSUE THREAD

**Issue by rmm-ch** [sdsc-ordes/saving-willy#18]
The error here on non-serialisable date objects: 
https://github.com/sdsc-ordes/saving-willy/blob/a87423374bf653803664c43f5dfd7eedb6d14dad/src/main.py#L92

Arises from the fact that there is now a date/time override in case the image metadata doesn't include anything. 

An immediate solution would be to cast these options to string in `input_handling.InputObservation.to_dict()`
```
            "date_option": str(self.date_option),
            "time_option": str(self.time_option),
```
But this will transmit a dict that includes date_option and time_option, which are probably not expected by the json databank, though the downstream processing might silently skip un-expected key/value pairs. 

The real fix should be to write the logic to that sensibly combines the metadata + manual overrides.

**Comment by vancauwe** [comment]
fixed by commit: https://github.com/sdsc-ordes/saving-willy/commit/7c16c6ecc4f1fc7868ecbee85bbc9ae4b448c297
